# Generated by Django 5.1.5 on 2025-03-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
