# Generated by Django 5.1.5 on 2025-03-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
